# Generated by Django 5.0.2 on 2024-11-19 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
